name: StackOverflow Login
on:
  schedule:
  - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: docker://guillaumefalourd/ritchiecli:py-3.8
    steps:
      - name: Install Chrome Driver
        run: |
            sudo apt-get update
            sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4 gnupg2
            sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
            sudo echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get -y update
            sudo apt-get -y install google-chrome-stable
            wget -N https://chromedriver.storage.googleapis.com/89.0.4389.23/chromedriver_linux64.zip -P ~/
            unzip ~/chromedriver_linux64.zip -d ~/
            rm ~/chromedriver_linux64.zip
            sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
            sudo chown root:root /usr/local/bin/chromedriver
            sudo chmod 0755 /usr/local/bin/chromedriver
      
      - name: Ritchie Formula StackOverflow login (Python) Execution
        env:
            RIT_STACKOVERFLOW_EMAIL: ${{ secrets.RIT_STACKOVERFLOW_EMAIL }}
            RIT_STACKOVERFLOW_PASSWORD: ${{ secrets.RIT_STACKOVERFLOW_PASSWORD }}
            RIT_STACKOVERFLOW_DISPLAY_NAME: ${{ secrets.RIT_STACKOVERFLOW_DISPLAY_NAME }}          
        run: |
            sudo rit add repo --provider="Github" --name="formulas-python" --repoUrl="https://github.com/GuillaumeFalourd/formulas-python" --priority=1
            sudo rit set credential --provider=stackoverflow --fields=email,password,displayname --values="$RIT_STACKOVERFLOW_EMAIL","$RIT_STACKOVERFLOW_PASSWORD","$RIT_STACKOVERFLOW_DISPLAY_NAME"
            sudo rit stackoverflow login